### ISSUE TITLE
Add SFTP support

### ISSUE THREAD

**Issue by voltagex** [tatsuhiro-t/aria2#308]
Currently it seems like only lftp can do segmented downloads via sftp. It would be great to add support to aria2

**Comment by Gelob** [comment]
I'd love to have this supported as well

**Comment by voltagex** [comment]
I'm looking into getting this done as paid development (not by me). Does anyone want to chip in and is this ok, @tatsuhiro-t?

**Comment by tatsuhiro-t** [comment]
I am not interested in sftp support right now, but we are open to accept patches.
libssh2 looks promising.

**Comment by scottjl** [comment]
old issue, but i'd love to see it added too.

**Comment by tatsuhiro-t** [comment]
Because of popular demand, we added basic sftp support.  Check out latest master branch.
sftp support depends on libssh2.  For debian and ubuntu users, install libssh2-1-dev package via apt-get.
Currently, we don't check server's fingerprint for known hosts.
We'll add feature to validate it against local file (e.g., $(HOME)/.ssh/known_hosts).
Since we added sftp, I close this issue.
Please submit sftp specific issues in separate thread.  Thank you.
