### ISSUE TITLE
Clarify encyption options

### ISSUE THREAD

**Issue by wernight** [tatsuhiro-t/aria2#318]
`--bt-require-crypto` and `--bt-min-crypto-level=arc4` seem, from the name, to do pretty much the same thing but from the code it seems they do different things. Could describe if one implies or requires to later.

**Comment by wernight** [comment]
If I understood correct here is a suggestion:

`--bt-require-crypto` to only accept encrypt incoming connections (outgoing connection may still remain un-encrypted, see --bt-min-crypto-level for that).
`--bt-min-crypto-level` specify the encryption level for incoming and outgoing connections; can be either `clear` (no encryption) or `XXX` (requires encrypted).

May be I missed something. I don't understand the reason one would want to set `--bt-require-crypto`, especially supposing that `--bt-min-crypto-level` implies `--bt-require-crypto`. Also the standard apps have an option `prefer encrypted` which seems missing.

**Comment by wernight** [comment]
Ah yes of course, thinking of it you may want to allow unencrypted in and force encryption out; that would be if `--bt-min-crypto-level` is only for outgoing connections

**Comment by tatsuhiro-t** [comment]
Thank you for the suggestion.

I finally read the related code and can give the more details.
For outgoing connection, aria2 always try encrypted handshake first.
If it fails and --bt-require-crypto is false, aria2 try unencrypted, legacy handshake.
For incoming connection, if --bt-require-crypto is false, aria2 accepts both encrypted and unencrypted handshake.  Otherwise, it only accepts encrypted one and reject unencrypted.

--bt-min-crypto-level is only considered when encrypted handshake is used.
For outgoing connection, if --bt-min-crypto-level is plain, aria2 includes both plain and arc4.
Otherwise only arc4 is included (thus encryption is enforced).
For incoming connection, aria2 always choose arc4 if peer offers it regardless of --bt-min-crypto-level option.  aria2 only choose plain If --bt-min-crypto-level is plain and arc4 is not offered by peer.

So both options affects both outgoing and incoming connections and they are orthogonal.

I don't know how other client implements prefer encryption, but the default behavior of aria2 prefers encryption if it is available.

**Comment by wernight** [comment]
I made a table from your comment: https://docs.google.com/a/beroux.com/spreadsheets/d/1rIpfH5AZ7wQ5RBQ3U2rXkvoUVPo_fM3WiEZTZM6o9_E/edit?usp=sharing

Am I to understand that 'plain' is actually that "simple" encryption level of torrent, and arc4 is a newer and stronger encryption?

**Comment by tatsuhiro-t** [comment]
The document looks good.

Plain mains no encryption. arc4 is encryption method used in BitTorrent MSE (message stream encryption, http://en.wikipedia.org/wiki/BitTorrent_protocol_encryption).

**Comment by wernight** [comment]
Updated the sheet; if plain means non-encrypted, I don't see the difference in `--bt-min-crypto-level`

**Comment by tatsuhiro-t** [comment]
If you call "encrypted handshake"  as just "encryption", there is not much difference.
But we have message payload encryption separately and it will be negotiated in encrypted handshake and peers agree on whether plain or arc4 is used.
--bt-min-crypto-level changes behavior of this negotiation.

1. --bt-require-crypto=false and --bt-min-crypto-level=plain:
  Both encrypted handshake and legacy handshake are accepted and tried.
  If encrypted handshake is used, plain method is acceptable.
2. --bt-require-crypto=false and --bt-min-crypto-level=arc4:
  Both encrypted handshake and legacy handshake are accepted and tried.
  If encrypted handshake is used, plain method is not acceptable. arc4  is the only choice.
3. --bt-require-crypto=true and --bt-min-crypto-level=plain:
  Only encrypted handshake is accepted and tried.
  Plain method is acceptable.
4. --bt-require-crypto=true and --bt-min-crypto-level=arc4:
  Only encrypted handshake is accepted and tried.
  Plain method is not acceptable. arc4 is the only choice.

Rephrase my comment:
--bt-min-crypto-level is only considered when encrypted handshake is used.
For outgoing connection, if --bt-min-crypto-level is plain, aria2 includes both plain and arc4.
Otherwise only arc4 is included (thus encryption is enforced).
For incoming connection, aria2 always choose arc4 if peer offers it regardless of --bt-min-crypto-level option. aria2 only choose plain If --bt-min-crypto-level is plain and arc4 is not offered by peer.

**Comment by wernight** [comment]
aria2 prefers encryption in all cases which is good.

So for `--bt-require-crypto=false --bt-min-crypto-level=arc4` with an unencrypted handshake, it'll still use an unencrypted payload?

And for `--bt-require-crypto=true --bt-min-crypto-level=plain` it means that handshake is encrypted, but payload may be unencrypted?

**Comment by tatsuhiro-t** [comment]
> So for --bt-require-crypto=false --bt-min-crypto-level=arc4 with an unencrypted handshake, it'll still use an unencrypted payload?

Yes.  Because unencrypted handshake (i.e. legacy handshake) does not have encryption option at all and --bt-min-crypto-level works with encrypted handshake only.

> And for --bt-require-crypto=true --bt-min-crypto-level=plain it means that handshake is encrypted, but payload may be unencrypted?

Yes, only if peer offers only plain method.  If peer offers arc4, aria2 selects it.

**Comment by wernight** [comment]
Thanks it's a lot clearer. Technically it probably makes sense, but for a user it seems to make little sense to have `--bt-require-crypto=false --bt-min-crypto-level=arc4`. Forcing encrypted handshake while allowing unencrypted payload (ie, `--bt-require-crypto=true --bt-min-crypto-level=plain`) can make some sense though it seems like a rare case.

So in short `--bt-require-crypto` force an encrypted handshake, while `--bt-min-crypto-level` forces an encrypted payload (currently only for encrypted handshakes).

What I would suggest is to simplify by either:
 * Having a single flag to simply force all encryption (ie, `--bt-require-crypto=true --bt-min-crypto-level=arc4`), or
 * A solution where `--bt-min-crypto-level=arc4` implies `--bt-require-crypto` so that  `--bt-min-crypto-level` would actually mean to force payload encryption (which means that handshake has also to be encrypted).
 * A third solution, would be a single flag `--bt-encryption` which can one of `plain`, `handshake-only`, or `all`.

Among those solution, I'd go for the simplest, the first, as I no case where I would for encryption of only the header if 99% of clients which can and are willing to encrypt header can and are willing to also encrypt the payload in ARC4.

**Comment by tatsuhiro-t** [comment]
I'm fine with the first solution.
We left these 2 options for backward compatibility and may add deprecated warning.

**Comment by tatsuhiro-t** [comment]
Added --bt-force-encryption option (c653c72), which does the first solution.

**Comment by wernight** [comment]
Very nice. Should the old fields be marked as deprecated?

**Comment by tatsuhiro-t** [comment]
I'd like to defer deprecation of these options, since they are valid working options, just rather too technical.
