### ISSUE TITLE
WinTLS encryption failure in version >=1.18.8

### ISSUE THREAD

**Issue by Nisto** [tatsuhiro-t/aria2#351]
Since version 1.18.8, aria2c has been complaining about WinTLS being unable to "encrypt a message" and that the "local security authority" could not be contacted. I have double checked previous versions against the latest (1.18.10) and there definitely appears to be an issue in aria2c itself and not my OS/browser settings or anything like that. I tried the different aria2c versions on both my standard OS installation and a clean VM installation with the same OS (Windows XP SP3) and the results are the same.

However, it seems the issue is mostly with larger sites like Google, Dropbox and probably any other sites that uses "proper" encryption and are "up to date" so to speak.

Here is an example session:

![aria2c](https://cloud.githubusercontent.com/assets/3769056/6616808/70969818-c8b2-11e4-8054-df03c908ba7d.png)

The full commandline from the image:
```
aria2c.exe --no-conf=false --conf-path=.\aria2.conf --input-file=C:\DOCUME~1\Nisto\LOCALS~1\Temp\flashgot.xdrodj9c.default\flashgot.fgt --dir=E:\tls-test --out=sh1psf.rar --referer=https://www.dropbox.com/home/Public/misc --load-cookies=C:\DOCUME~1\Nisto\LOCALS~1\Temp\flashgot.xdrodj9c.default\cookies-9 "--user-agent=Mozilla/5.0 (Windows NT 5.1; rv:36.0) Gecko/20100101 Firefox/36.0"
```

And my configuration file looks like this:
```
referer=*

force-sequential=false
min-split-size=5M
split=5
max-connection-per-server=16
stream-piece-selector=inorder

check-certificate=false
remote-time=true

no-file-allocation-limit=100M
allow-overwrite=false
auto-file-renaming=true

max-resume-failure-tries=1
always-resume=false

summary-interval=0
download-result=full
```

**Comment by nmaier** [comment]
XP is not supported with WinTLS for various reasons, most importantly because XP is not supported any longer and the underlying Schannel in XP lacks a lot of features so that it is impossible to use it securely.
Essentially Schannel on XP, is broken crypto and with it all software that uses it for anything except to access the certificate store, e.g. Internet Explorer.
As such, I won't be "fixing" WinTLS to be compatible with XP, nor will I accept patchs or recommend to accept patches that do so.

Please consider using either a vendor-supported OS, or build aria2 yourself with the OpenSSL or GnuTLS backend.

**Comment by tatsuhiro-t** [comment]
I support @nmaier 's decision.

**Comment by Nisto** [comment]
You can't add an option to at least suppress these TLS/SSL encryption warnings/errors by any chance? Like maybe a new `--console-log-level=` option?

**Comment by nmaier** [comment]
I can suppress the warnings, but it still won't work because Schannel, the OS-level TLS implementation WinTLS uses, does not have the features aria2c needs under XP.

**Comment by Nisto** [comment]
The suppression of the warnings was all I asked for. I hope you can add it in the next release.
