### ISSUE TITLE
How to use libaria2 to download page to string synchronously like with libcurl?

### ISSUE THREAD

**Issue by zelid** [tatsuhiro-t/aria2#389]
Libaria2 is used as a cool async download manager!

In the same program there is a need to download the webpage to a string and do some parsing of download links before feeding them to libaria2.

Adding dependancy on curl just to read webpage to a string looks like a bad idea.

What is a good way to use libaria2 to download webpage to a string?
Something like described here for curl http://techoverflow.net/blog/2013/03/15/c-simple-http-download-using-libcurl-easy-api/

I tried to do something like this with passing `is_finished` flag through lambda capture and wait for this flag in infinite loop to return but as soon as any reference is passed to lambda I get download handler callback type missmatch. I'm C++ newbie, but that's what I tried:

```
std::string download_url(std::string url) {

    aria2::libraryInit();
    aria2::Session* session;
    aria2::SessionConfig config;

    bool is_done = false;
    std::string content;

    config.downloadEventCallback = [&is_done, &content](aria2::Session* session , aria2::DownloadEvent event , aria2::A2Gid gid, void* userData) mutable -> int  {

        if (event == aria2::EVENT_ON_DOWNLOAD_COMPLETE) {
            aria2::DownloadHandle* dh = aria2::getDownloadHandle(session, gid);
            if(!dh) return 0;
            if(dh->getNumFiles() > 0) {
                aria2::FileData f = dh->getFile(1);
                if(!f.path.empty()) {
                    std::string filename = f.path;

                    // read downloaded file content to string
                    content = get_file_contents(filename);
                    // mark that we are ready so infinite loop can stop and return
                    is_done = true;

                }
            }
            aria2::deleteDownloadHandle(dh);
        }

        return 0;
    };
    session = aria2::sessionNew(aria2::KeyVals(), config);

    std::vector<std::string> uris = {url};
    aria2::KeyVals options;
    aria2::addUri(session, nullptr, uris, options);

    int rv;
    for(;;) {
        rv = aria2::run(session, aria2::RUN_ONCE);
        if(rv != 1) {
            break;
        }

    }
    rv = aria2::sessionFinal(session);
    aria2::libraryDeinit();

    for(;;) {
        if (is_done)
            return content;
    }
}
```

**Comment by tatsuhiro-t** [comment]
`config.downloadEventCallback` is pure C function pointer.  If we capture anything in C++ lambda, they cannot be used as function pointer anymore.  Ideally, we should provide callback using `std::function<>` so that these lambda works.  But currently, it isn't.  Usually, we assign pointer to some user defined struct or class to `SessionConfig.userData`, and it is then passed in callback as `userData` parameter.

We can add new download in the callback.  So if it is feasible, you can parse downloaded HTML in callback, and then use `aria2::addUri` to add extracted links to aria2 session.  Then aria2 continues to download these things, and once they are all downloaded, it will stop.
