### ISSUE TITLE
Maybe memory leak

### ISSUE THREAD

**Issue by hagrid-the-developer** [tatsuhiro-t/aria2#394]
Hello.
I am using aria2 for the first time, it is possible that I did something wrong, but it looks to me that aria2 contains some memory leak.

I did a test with arai2 under Linux, when I tried to download ~3M small files through ftp over local network. I started aria2 in rpc mode and call aria2.addUri() . From time to time I called aria2.purgeDownloadResult(). Memory consumption was slowly growing up to 4GB, when aria2 was killed by Linux. When purgeDownloadResult() was called, then RequestGroupMan::downloadResults_.size() == 0, but used memory didn't decrease.

**Comment by tatsuhiro-t** [comment]
Thank you.  From you description, it looks like memory leak bug.  We have to first reproduce it in our development environment.
I think you are using latest version of aria2 (1.19.0), is that correct?  Also ftp is plain ftp, not sftp, is that correct?
Could you tell us the command-line parameter for aria2c, and options values for aria2.addUri() ?

**Comment by tatsuhiro-t** [comment]
I observed that if there was an error while downloading file, the memory usage was increasing.
This behaiour is only seen for FTP download, not for HTTP.

**Comment by hagrid-the-developer** [comment]
I used aria from github, commit 89c1916fa57d87ea09142cc3588044c691d1928f.
I used plain ftp, arai2c was started this way:

    $ /opt/aria2/bin/aria2c --enable-rpc=true

addUri command (part of python code):

    uri = 'ftp://user:pass@...'
    jsonreq = json.dumps({'jsonrpc':'2.0', 'id':'qwer', 'method':'aria2.addUri', 'params':[[uri]]})
    c = urllib2.urlopen('http://localhost:6800/jsonrpc', jsonreq)

**Comment by tatsuhiro-t** [comment]
Thanks.  After further investigation, the huge memory usage is caused by the 3M downloads registered into aria2c.  The each download object is rather large in aria2, and when RPC is used, all queued downloads are kept in memory.  It quickly fills up memory if you requests 3M downloads.
You mentioned that clearing download results does not decrease memory.  This is the expected behaviour of the standard memory allocator for libc.  There seems to be complicated story behind that, but it seems that aria2's memory allocation pattern is not suitable for this allocator.  aria2 supports alternative allocator, jemalloc, using --with-jemalloc, which can be more responsive for freeing memory.

So adding 3M downloads at once to aria2c via RPC is not feasible at the moment.  If RPC is a must, we have to split them into groups, say, each 10000 downloads.
If RPC is not must, and you can run aria2 in command-line directly, --input and --deferred-input options would work.

**Comment by hongyi-zhao** [comment]
By saying that: --input   and --deferred-input options would work.

Do you mean: --input-file   and --deferred-input options would work?

Regards
H.Zhao

**Comment by tatsuhiro-t** [comment]
Yes.  I forgot to proper name for the option I added several years ago ;)

**Comment by hagrid-the-developer** [comment]
Everything seems to be working to me. Thanks for the hint with jemalloc.
