### ISSUE TITLE
--file-allocation=none and --file-allocation=trunc

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#406]
Hi Tatsuhiro,

In the manpage, I can find the following depictions:

   --file-allocation=<METHOD>
    Specify  file allocation method.  none doesn't pre-allocate file
    space.
   [snip]
     trunc uses ftruncate(2) system call or platform-specific
     counterpart to truncate a file to a specified length.

But, I still cann't figure out for which cases, should I use the --file-allocation=none and --file-allocation=trunc methods for my downloading.  Any hints?

Regards

**Comment by tatsuhiro-t** [comment]
Using --file-allocation=trunc can set file length, but actually not consuming disk space.  Both require file system which supports sparse files.

**Comment by hongyi-zhao** [comment]
I still not so clear on the purpose of  --file-allocation=trunc, especially for the following things:
 [1] Considering that the file length is determined by the contents of a file and is a attribute of file itself, so what's the purpose of setting file length?

[2] If you setting the  file length, the length must be given as a digital string as the argument, anyway,  ``--file-allocation=trunc`` doesn't accept the argument of the file's length string.

Any hints?

**Comment by tatsuhiro-t** [comment]
> [1] Considering that the file length is determined by the contents of a file and is a attribute of file itself, so what's the purpose of setting file length?

file length is determined by the content-length or meta-data from remote server or something.  If you want this length is applied to local file, then use trunc, otherwise use something else.

> [2] If you setting the file length, the length must be given as a digital string as the argument, anyway, --file-allocation=trunc doesn't accept the argument of the file's length string.

file length is determined by the content-length or meta-data from remote server, and user cannot set it by hand.

If you are using, linux and recent file system (like ext4), just use "falloc", which is default.
For WIndows users and NTFS fs, "falloc" works fine too.
For VFAT users, they must use prealloc, since it lacks sparse file support.

If you don't want to allocate fully disk space, use none or trunc.  If you don't care the provisional length of a file, use none, otherwise use trunc.

**Comment by hongyi-zhao** [comment]
In fact, I want to obtain the real downloaded bytes of a file at the specific time point.

It seems all of the file-allocation methods don't reflect the  real downloaded bytes of a file at that moment.  Of course, the file-allocation methods are designed for high efficient for allocating real-time data into the destination files. So, the purpose I wanted to obtain  real-time downloaded bytes of a file at the specific time point, cann't be obtained by this method.

BTW, according to your depictions, all of the file-allocation methods which supporting sparse file are similar to the operations done by dd's --conv=notrunc options.

Regards

**Comment by hongyi-zhao** [comment]
One more issue:

Just as I've posted in another threads, is there some convenient method for me to konw the real-time downloaded bytes of a file at the specific time point?

Regards

**Comment by tatsuhiro-t** [comment]
Use RPC interface.  http://aria2.sourceforge.net/manual/en/html/aria2c.html#rpc-interface
