### ISSUE TITLE
bcrypt.dll missing in POS ready 2009 with last aria2-1.19.0

### ISSUE THREAD

**Issue by blato** [tatsuhiro-t/aria2#449]
This application has failed to start because bcrypt.dll was not found.
OS is not outdate https://support.microsoft.com/en-us/lifecycle?p1=14086
Prevous version aria2-1.18.10-win-32bit-build1 starting without bcrypt.dll

**Comment by clamsawd** [comment]
@blato Windows Embedded POSReady 2009 have the same problem that Windows XP, this issue was commented #393. The difference between 1.18.10 and 1.19.0 version is the SFTP support, when you enable SFTP (libssh) on aria2 build for Windows, it need bcrypt.dll to work. To fix this problem, I'm compiling a version with SFTP (for Windows Vista and Later) and other without SFTP to preserve the compatibility with Windows XP (and your system).

This package should work in Windows Embedded POSReady 2009:

* [aria2-1.19.2-win-xp-build1.7z] (https://github.com/clamsawd/aria2-static-builds/raw/master/builds/aria2-1.19.2-win-xp-build1.7z) (with OpenSSL)

Also, every aria2 new versions released will be compiled and published in https://github.com/clamsawd/aria2-static-builds

**Comment by tatsuhiro-t** [comment]
#393 will fix this issue.
