### ISSUE TITLE
Stuck at 99%

### ISSUE THREAD

**Issue by gerases** [tatsuhiro-t/aria2#550]
I'm giving aria2 a try. I have 4 VMs. I created a torrent for a 1G file. I seeded the torrent with

`aria2c -V path_to_torrent`

I enabled the RPC feature on the other 3VMs. I added the same torrent through an RPC call and they all started downloading. But they consistently stop at 99% and nothing is happening BUT the file on the hard drive is already complete. So somehow `aria2c` doesn't know it has downloaded all of the content?

The `tellActive` RPC call says:

```
  "files"=>
   [{"completedLength"=>"1068302336",
     "index"=>"1",
     "length"=>"1073741824",
     "path"=>"/home/aria2/Downloads/1g_file",
     "selected"=>"true",
     "uris"=>[]}],
```

And `ls -l /home/aria2/Downloads/1g_file` shows `1073741824`.

The status line looks like this:

`[#8b9e1d 0.9GiB/1.0GiB(99%) CN:0 SD:0 DL:0B UL:0B(88MiB)]`

What could be the reason for this?

Thanks.

**Comment by tatsuhiro-t** [comment]
aria2 allocate file in file system before download by default.  The actual file size does not necessarily means the file is downloaded completely.  The actual downloaded size is "completedLength", which is 1068302336.  It is less than 1073741824, so download is incomplete.

We have similar bug report in #517.  We have fixed relevant bug since the last release.  If you can compile aria2 from git repository, then it is worth trying.

Please note that aria2 by default sets seed-ratio 1.0, which means aria2 exists as soon as the upload size equals file size (in this case, 1GB).  Try --seed-ratio option to set bigger size, or 0 which means unlimited.

**Comment by gerases** [comment]
Thanks much for a quick response. I think I solved the problem. When I set the ratio to 0.0 on the original seeder, it worked fine. I will definitely compile using the git repo though just in case.

Thanks again.

**Comment by Reedwarbler** [comment]
I am using the
