### ISSUE TITLE
Initializing the seeding

### ISSUE THREAD

**Issue by gerases** [tatsuhiro-t/aria2#556]
Hi,

I was wondering if there's a way to start seeding through the RPC instead of with the `-V` switch on the command line.

I would ideally like to start `aria2` on all my machines and start seeding on one of them though an RPC call. Is that possible? Otherwise, what's the best practice?

Thanks

**Comment by kkartaltepe** [comment]
I simply run aria2 with `check-integrity=true` in my config. Then to seed a torrent I have already downloaded I simply use the `addTorrent` rpc call and set the directory (using the `options` parameter) to where ever the files already exist. It should check integrity and then begin seeding. You could also set the `check-integrity=true` in the `options` parameter instead of setting it globally.

**Comment by gerases** [comment]
Ahh, very nice! It does seem to work. What also worked was setting `bt-seed-unverified` to true. But it sounds like not the best idea. Once I specified `check-integrity=true`, it started working.

**Comment by tatsuhiro-t** [comment]
@kkartaltepe thank you for answering the question!
