### ISSUE TITLE
DHT seeding

### ISSUE THREAD

**Issue by gerases** [tatsuhiro-t/aria2#559]
Hi,

I can't find this information anywhere and I've scoured everything I could on this topic - DHT seeding.

1. First, I don't see anything anywhere on creating a trackerless torrent. I think `transmission-cli` is the closest thing I've found. Is that the recommended way? Other **cli** tools fit for this job specifically?

2. I can't figure out how the process actually works. That probably should be described better in the documentation. Say I have 4 machines and all of them are using `DHT`. `aria2c` is running as a daemon on all 4. What would be the approximate sequence of steps for them exchange a brand new file? 

I see `--dht-entry-point` and I think that's in the play somehow, but I"m not sure if I'm missing something fundamental to make it all work.

Thanks much!!

P.S.: Is the github/issues interface a good place to start these questions or there's a forum?

**Comment by tatsuhiro-t** [comment]
If my understanding is correct, you are in the closed network, and you have 4 aria2 daemon enabling DHT.

First, you need one aria2c as seeder.  You can run aria2 as seeder with -V option and enable DHT.
For other aria2 daemons, run --dht-entry-point to the IP address of bootstrap node of DHT network.  Since your DHT network is in your closed network, and your only node is aria2 seeder, specify seeder's IP address and DHT port in --dht-entry-point option.  You need magnet URI to these leechers.  You can see magnet URI using `aria2c -S /path/to/file.torrent`.

We have no discussion forum.  Use this issue for anything related to aria2.

**Comment by gerases** [comment]
Nice!! 

Yes, that's a closed network of 4 machines for testing purposes.

> First, you need one aria2c as seeder. You can run aria2 as seeder with -V option and enable DHT.
> For other aria2 daemons, run --dht-entry-point to the IP address of bootstrap node of DHT network. Since your DHT network is in your closed network, and your only node is aria2 seeder, specify seeder's IP address and DHT port in --dht-entry-point option.

That's what I did kind of except I didn't specify the DHT port. I will try that. 

> You need magnet URI to these leechers.

I'm a bit unclear on why I need a magnet URI in this case?

Thanks!!

**Comment by tatsuhiro-t** [comment]
Ah, no, you have .torrent file, then you can use it.  No need to use magnet URI.

**Comment by gerases** [comment]
Perfect! Thank you, I will give it a try!
