### ISSUE TITLE
Config file in Windows for max connections/default directory

### ISSUE THREAD

**Issue by Sphincone** [tatsuhiro-t/aria2#589]
I can't find the config file for aria2 in my windows installation. I want to change the max connection number for downloads and want to change the default directory to something like C:/Downloads rather than the default C;/Windows/System32/ (When I run CMD using admin).

**Comment by tatsuhiro-t** [comment]
It is usually %USERPROFILE% points to.

**Comment by Sphincone** [comment]
But I couldn't find it anywhere, not even in %userprofile% :|

**Comment by tatsuhiro-t** [comment]
It is not created automatically.  You have to create `.aria2` directory, and place `aria2.conf` inside it.

**Comment by Sphincone** [comment]
That worked. Thank you!

To add something here, normally creating a folder named `.aria2` will not work in Windows. To create, just write `.aria2.` (yes, dot in both prefix and suffix to create the folder.

**Comment by Kozi801** [comment]
Thank you so much, I have been breaking my head for hours and hours on days to find why it did not work. I needed to do one dot before and one after (note that the second dote becomes hidden after? I dont know why. it then look as .aria2 instead of .aria2.) (apparently this is a linux unix type of naming convention right?  I really need to learn Linux :D

**Comment by Barafu** [comment]
I just created a folder ".aria2" and inside it a file "aria2.conf".  No extra dots. Everything works.
