### ISSUE TITLE
aria2c cann't resume the downloading process for VPN-Gate-Client.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#590]
Hi Tatsuhiro,

When I downloading the VPN Gate Client from here: http://www.vpngate.net/en/download.aspx
as follows:

$ aria2c http://download.vpngate.jp/common/cd.aspx/vpngate-client-2016.03.09-build-9605.134952.zip

I find that the downloading process cann't be resumed after stop.  The error is as follows:

      -> [DefaultBtProgressInfoFile.cc:277] errorCode=1 total length mismatch. expected: 54126669, actual: 54125162

The file's url don't change, but the total length mismatch.  Why?

Regards

**Comment by tatsuhiro-t** [comment]
This means that server refused to accept range request, which means you cannot resume downloads.  This is not aria2 bug.

**Comment by tatsuhiro-t** [comment]
So why we got that kind of error message:  we really don't know server supports range request (resuming), so we just issue request expecting server supports it.  Since this is resume, the expected content-length is smaller than total length (file length).  But it turns out that server does not support resume, and it returns full file content.  Then aria2 complains because the expected file size does not match.  We don't overwrite user's file in this case, since deleting file is the last thing user wants.

**Comment by tatsuhiro-t** [comment]
I found that that sever returns random content length.  In this case, we cannot resume download.

**Comment by hongyi-zhao** [comment]
Thanks a lot.
