### ISSUE TITLE
suggestions around --file-allocation

### ISSUE THREAD

**Issue by Twilight** [tatsuhiro-t/aria2#594]
the default prealloc is too slow, why trunc is not default? are there any drawbacks? it works pretty nice for me.

I specified allocation method other than falloc, but the windows build still warn like this:
````
[WARN] Gaining privilege SeManageVolumePrivilege failed.
[WARN] --file-allocation=falloc will not work properly.
````
I think this should be silenced in this situation.

**Comment by tatsuhiro-t** [comment]
trunc does not allocate file space.  It just set file length in metadata.  So it could be fragmented if aria2 write data in random order.

For warning, we chose the easiest way for now.  Since user can specify falloc in RPC we don't know privilege is required in advance.  Perhaps, we can do this on demand.

**Comment by Twilight** [comment]
that makes sense, I think we should have that info about trunced file been fragmented in the documentation.

**Comment by tatsuhiro-t** [comment]
The warning now deferred until falloc is specified by option as of 1126722.
The implication of fragmentation with trunc has already been described in http://aria2.github.io/manual/en/html/aria2c.html#cmdoption--file-allocation

Closing this issue.
